#
# Copyright (c) 2016 Samsung Electronics Co., Ltd. All rights reserved.
# Heesub Shin <heesub.shin@samsung.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= artik05x.o
obj-$(CONFIG_SECURE_BOOT) += artik05x_secure.o
